[build]
  publish = "dist/healthyfood"
  command = "ng build --configuration production --aot"
  
[[redirects]]
  from = "/*"
  to = "src/index.html"
  status = 200

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "https://apihealthyfood.netlify.app" 